# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mng_dashboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, validators=[mng_dashboard.models.validate_emp_mail])),
                ('active', models.NullBooleanField()),
                ('int_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Productivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result', models.IntegerField(choices=[(1, b'Customer Reached'), (2, b'Customer Not Reached'), (3, b'Try Again Later'), (4, b'Message Left')])),
                ('type', models.IntegerField(choices=[(1, b'Inbound call'), (2, b'Outbound call'), (3, b'Inbound email'), (4, b'Outbound email')])),
                ('clerk', models.ManyToManyField(to='mng_dashboard.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result', models.IntegerField()),
                ('unallocated_cash', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, b'Madrid'), (2, b'Barcelona'), (3, b'Valencia'), (4, b'Alicante'), (5, b'Bilbao'), (6, b'Zaragoza'), (7, b'Malaga'), (8, b'Sevilla'), (9, b'GLOBAL')])),
                ('code', models.IntegerField(choices=[(1, b'MAD'), (2, b'BCN'), (3, b'VLC'), (4, b'ALC'), (5, b'BIO'), (6, b'ZAZ'), (7, b'AGP'), (8, b'SVQ'), (9, b'OVERDUE RECEIVABLES')])),
                ('clerks', models.ManyToManyField(to='mng_dashboard.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TimeExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.IntegerField(choices=[(1, b'Sick Leave'), (2, b'Vacation'), (3, b'Training'), (4, b'Overtime')])),
                ('clerks', models.ManyToManyField(to='mng_dashboard.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='results',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mng_dashboard.Territory'),
        ),
    ]
