# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.NullBooleanField(default=True),
        ),
    ]
