# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 09:12
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations import RunPython

from mng_dashboard.models import Territory


def populate_teritories(*args):

    territories = ['Madrid', 'Barcelona', 'Valencia', 'Alicante', 'Bilbao', 'Zaragoza', 'Malaga', 'Sevilla']
    for territory in territories:
        Territory.objects.create(name=territory)

class Migration(migrations.Migration):

    dependencies = [
        ('mng_dashboard', '0001_initial'),
    ]

    operations = [
        RunPython(populate_teritories)
    ]
