# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mng_dashboard', '0002_auto_20180318_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeexp',
            old_name='clerks',
            new_name='clerk',
        ),
    ]
