# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng_dashboard', '0003_auto_20180402_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailstatus',
            name='date',
            field=models.DateField(default='2018-01-01'),
            preserve_default=False,
        ),
    ]
